[phases.setup]
nixPkgs = ["python311", "gcc", "gfortran", "cmake", "pkg-config", "libGL", "libGLU", "mesa", "openblas", "lapack", "zlib"]

[phases.install]
cmds = ["pip install --upgrade pip setuptools wheel", "pip install numpy==1.26.4 --only-binary=numpy", "pip install -r requirements.txt"]

[start]
cmd = "gunicorn plagiarism.wsgi:application --timeout 120 --workers 2"